### ISSUE TITLE
Grupo 01 - Gerenciar Estoque

### ISSUE THREAD

**Issue by lglmoura** [PosGraducao-IFF-2014/Trabalho04#1]
cadastraEstoque(Estoque)

```
    Estoque = {codigo,descricao,localizao}

    DeleteEstoque (codigoEstoque)

verificar se exite algum produto cadastrado ProdutoEstoque

    listaEstoque( )

    consultaEstoque(codigoEstoque)
```

**Comment by d3rf** [comment]
Assumindo o Grupo 1

**Comment by d3rf** [comment]
"verificar se exite algum produto cadastrado ProdutoEstoque" seria pra listar ou para deletar ?

**Comment by d3rf** [comment]
"verificar se exite algum produto cadastrado ProdutoEstoque" seria pra listar ou para deletar ?
