### ISSUE TITLE
Grupo 07 - Gerenciar Compras

### ISSUE THREAD

**Issue by lglmoura** [PosGraducao-IFF-2014/Trabalho04#7]
adastrarCompra(Compra)

```
    Compra={codigoCompra ,{codigoProduto,quantidade},data,valortotal,codigoFornecedor}

    consultarCompra (codigoCompra )

    deletarCompra (codigoCompra )
```

**Comment by faelvs** [comment]
Rafael Vasconcelos

**Comment by rubensolv** [comment]
Favor inserir um serviço de consulta para validação da existência de um fornecedor em pelo menos alguma compra. 
Verificar a possibilidade deste método retornar apenas verdadeiro ou falso para a requisição, sendo verdadeiro caso exista e falso caso não exista em nenhuma compra.
Caso o método retorne apenas um Json com os dados também será de bom uso.
